### ISSUE TITLE
请问如果我是想通过视频流来训练该从哪些地方修改代码呢

### ISSUE THREAD

**Issue by woshiagan** [ricagj/train_your_own_game_AI#1]
因为无法保证一直有一个游戏运行且让ai去输出动作学习,所以想通过寻找到的视频里面比较厉害的动作让ai在空余时间通过视频流学习,
我需要修改代码里面关于哪些地方才可以实现

**Comment by ricagj** [comment]
~~~python

# game_player/run.py

# 第一个是替换掉while循环
# 第二个是替换掉图像输入

class Agent:
    def __init__(self):
        
        self.video = cv.VideoCapture('tmp.mp4')

        self.run()

        self.video.release()

    def round(self):

        ret, frame = self.video.read()

        # self.screens.append(get_game_screen())
        self.screens.append(frame)

    def run(self):

        while self.video.isOpened():

            self.round()

~~~

**Comment by woshiagan** [comment]
> ```python
> # game_player/run.py
> 
> # 第一个是替换掉while循环
> # 第二个是替换掉图像输入
> 
> class Agent:
>     def __init__(self):
>         
>         self.video = cv.VideoCapture('tmp.mp4')
> 
>         self.run()
> 
>         self.video.release()
> 
>     def round(self):
> 
>         ret, frame = self.video.read()
> 
>         # self.screens.append(get_game_screen())
>         self.screens.append(frame)
> 
>     def run(self):
> 
>         while self.video.isOpened():
> 
>             self.round()
> ```
对不起是我的描述错误,你是将视频流转换成截图发送给了智能体
我的意思是因为视频是不会在智能体发出动作后执行智能体的动作的,我是想通过yolo判断视频里的动作传递给智能体
图片还是作为智能体的反馈,但是动作选择那里由yolo这类cnn程序识别视频里面的动作代替原来的神经网络选择动作,然后训练完成以后保存为经验,下次智能体就可以学习这里面的经验

**Comment by ricagj** [comment]
~~~python

# https://github.com/ricagj/train_your_own_game_AI/blob/37cff4733536e882c8b9f35ccf4a1eb5f550132c/game_player/run.py#L139

# 制作经验包（数据集）

video ───────────────────────────────>
        │
        └─> frame ─> Yolo ──> action

# 重写保存经验和加载经验方法

def save():
    """
    store <- [frame, action, reward]
    """
    ...

def load():
    """
    参考
    """
    ...

def run():
    load()
    train()

~~~

**Comment by woshiagan** [comment]
非常感谢 我会自己去尝试
